### ISSUE TITLE
SSE function call on demand from QlikView

### ISSUE THREAD

**Issue by ThomasGorr** [qlik-oss/server-side-extension#41]
Hey, we are currently experimenting with SSEs in QlikView and in Qlik Sense.

Now at the moment we got a little bit stuck...
What we want to do is triggering a function call on demand from our Extension to the SSE.
We found a (hacky) way to do this in Qlik Sense by defining a SSE function call within a Hypercube.
But we do not find a way to do so in QlikView.
Do you may have an idea how to solve this?

**Comment by Bjornwa** [comment]
Hi Thomas,

The SSE functionality is there in order to extend the range of computations possible in Qlik's Associative Engine, so using SSE as a general communication mechanism can quickly stretch things into the field of 'hacks' - as you have already observed.

Your QlikView extension will need to follow the same pattern as the one for Qlik Sense and trigger a hypercube calculation with SSE as part of some kind of chart expression but how this is done will depend on what you already have and what you are trying to do. Any questions concerning QlikView extensions should of course be brought up in #qlikview-extensions on Qlik Branch slack or the QlikView Extensions space on community.

Happy hacking!

/Björn

**Comment by hansnull** [comment]
Maybe you could provide an example in this repository, how you "trigger a hypercube calculation with SSE" from client side javascript code in QlikView?

**Comment by paulcalvet** [comment]
> Hey, we are currently experimenting with SSEs in QlikView and in Qlik Sense.
> 
> Now at the moment we got a little bit stuck...
> What we want to do is triggering a function call on demand from our Extension to the SSE.
> We found a (hacky) way to do this in Qlik Sense by defining a SSE function call within a Hypercube.
> But we do not find a way to do so in QlikView.
> Do you may have an idea how to solve this?

Hi Thomas,
I want to call a function in Qlik Sense on demand with SSE.
Do you have an example of this implementation ?
Thanks
Paul

**Comment by qlik-aoh** [comment]
Hi @hansnull an @paulcalvet,

I have heard of users doing this in Qlik Sense but I am not aware of any who has done this in Qlikview. Unfortunately we do not have example, for either Sense or Qlikview, and creating such examples is currently not in any roadmap. 

I recommend asking this question in #sse on https://qlik-branch.slack.com/ (get an invite at https://qlikbranch-slack-invite.herokuapp.com/ ). There are several power users of SSE there who can advice.

Good luck!
/Markus

**Comment by paulcalvet** [comment]
> Hi @hansnull an @paulcalvet,
> 
> I have heard of users doing this in Qlik Sense but I am not aware of any who has done this in Qlikview. Unfortunately we do not have example, for either Sense or Qlikview, and creating such examples is currently not in any roadmap.
> 
> I recommend asking this question in #sse on https://qlik-branch.slack.com/ (get an invite at https://qlikbranch-slack-invite.herokuapp.com/ ). There are several power users of SSE there who can advice.
> 
> Good luck!
> /Markus

Hi Markus,
I found a solution, I will publish an extension on Qlik Branch.
https://github.com/paulcalvet/Qlik-Sense-Reload-Button
The solution is to create an hypercube in the extension, send the values to Python, destroy the hypercube and wait the callback :-)
Paul
